runtime: nodejs18

env_variables:
  NODE_ENV: production
  REACT_APP_API_URL: https://enterprisebackendltd.vercel.app/api

handlers:
- url: /static
  static_dir: build/static

- url: /(.*\.(json|ico|js))$
  static_files: build/\1
  upload: build/.*\.(json|ico|js)$

- url: .*
  static_files: build/index.html
  upload: build/index.html

automatic_scaling:
  min_instances: 0
  max_instances: 10